module.exports = {
  TRACKER_UNAUTHORIZED: 'TRACKER_UNAUTHORIZED',
  TRACKER_FORBIDDEN: 'TRACKER_FORBIDDEN',
  TRACKER_DEVICE_NOT_FOUND: 'TRACKER_DEVICE_NOT_FOUND',
  TRACKER_VALIDATION_ERROR: 'TRACKER_VALIDATION_ERROR',
  TRACKER_RANGE_TOO_LARGE: 'TRACKER_RANGE_TOO_LARGE',
  TRACKER_INTERNAL_ERROR: 'TRACKER_INTERNAL_ERROR',
  TRACKER_SERVICE_UNAVAILABLE: 'TRACKER_SERVICE_UNAVAILABLE',
};
